[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    "@paulrberg/contracts/math/=lib/prb-math/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@jbx-protocol/juice-nft-rewards=node_modules/@jbx-protocol/juice-nft-rewards",
    "@jbx-protocol/contracts-v2=node_modules/@jbx-protocol/contracts-v2"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config