[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'forge-test'
script = 'scripts'
optimizer_runs = 2000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config